language: ruby
before_install: gem install bundler && bundler --version
install: bundle install --jobs=3 --retry=3
before_script:
  - bundle install
  - bundle exec rake db:create db:schema:load
script: bundle exec rake
rvm:
  - 2.5.1
services:
  - postgresql
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
