default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_development
  username: jason
  password: jason
  host: localhost

test:
  <<: *default
  database: test

production:
  <<: *default
  database: twitter_production
  username: twitter
  password: <%= ENV['TWITTER_DATABASE_PASSWORD'] %>
